version: "2"
services:
  minio:
    # image: minio/minio:RELEASE.2020-07-31T03-39-05Z
    image: minio/minio
    volumes:
      - ./data:/data
      # - data1-1:/data1
      # - data1-2:/data2
    ports:
      - "9001:9000"
    environment:
      MINIO_BROWSER: 'off'
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    # command: server http://minio{1...4}/data{1...2}
    command: server /data
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    #   interval: 30s
    #   timeout: 20s
    #   retries: 3
  
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "3350:27017"
    volumes:
      - ./mongo/data:/data/db